name: amivi
description: "Aplicación Móvil de Inspección Vial Inteligente."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  uuid: ^4.3.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.0
  geolocator: ^13.0.0
  geocoding: ^2.2.1
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/adapters/out/ai/models/modelo_vial_correcto.tflite
    - lib/src/adapters/out/ai/models/modelo_vial_gradcam.tflite